// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package ru.spbu.astro;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .ru.spbu.astro.msg sons = 1;
    java.util.List<ru.spbu.astro.Schema.msg> 
        getSonsList();
    ru.spbu.astro.Schema.msg getSons(int index);
    int getSonsCount();
    java.util.List<? extends ru.spbu.astro.Schema.msgOrBuilder> 
        getSonsOrBuilderList();
    ru.spbu.astro.Schema.msgOrBuilder getSonsOrBuilder(
        int index);
    
    // optional .ru.spbu.astro.msg.RTreeMessage rTree = 2;
    boolean hasRTree();
    ru.spbu.astro.Schema.msg.RTreeMessage getRTree();
    ru.spbu.astro.Schema.msg.RTreeMessageOrBuilder getRTreeOrBuilder();
  }
  public static final class msg extends
      com.google.protobuf.GeneratedMessage
      implements msgOrBuilder {
    // Use msg.newBuilder() to construct.
    private msg(Builder builder) {
      super(builder);
    }
    private msg(boolean noInit) {}
    
    private static final msg defaultInstance;
    public static msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_fieldAccessorTable;
    }
    
    public interface RTreeMessageOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    public static final class RTreeMessage extends
        com.google.protobuf.GeneratedMessage
        implements RTreeMessageOrBuilder {
      // Use RTreeMessage.newBuilder() to construct.
      private RTreeMessage(Builder builder) {
        super(builder);
      }
      private RTreeMessage(boolean noInit) {}
      
      private static final RTreeMessage defaultInstance;
      public static RTreeMessage getDefaultInstance() {
        return defaultInstance;
      }
      
      public RTreeMessage getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_RTreeMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_RTreeMessage_fieldAccessorTable;
      }
      
      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ru.spbu.astro.Schema.msg.RTreeMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ru.spbu.astro.Schema.msg.RTreeMessage prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ru.spbu.astro.Schema.msg.RTreeMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_RTreeMessage_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_RTreeMessage_fieldAccessorTable;
        }
        
        // Construct using ru.spbu.astro.Schema.msg.RTreeMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ru.spbu.astro.Schema.msg.RTreeMessage.getDescriptor();
        }
        
        public ru.spbu.astro.Schema.msg.RTreeMessage getDefaultInstanceForType() {
          return ru.spbu.astro.Schema.msg.RTreeMessage.getDefaultInstance();
        }
        
        public ru.spbu.astro.Schema.msg.RTreeMessage build() {
          ru.spbu.astro.Schema.msg.RTreeMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private ru.spbu.astro.Schema.msg.RTreeMessage buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          ru.spbu.astro.Schema.msg.RTreeMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public ru.spbu.astro.Schema.msg.RTreeMessage buildPartial() {
          ru.spbu.astro.Schema.msg.RTreeMessage result = new ru.spbu.astro.Schema.msg.RTreeMessage(this);
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ru.spbu.astro.Schema.msg.RTreeMessage) {
            return mergeFrom((ru.spbu.astro.Schema.msg.RTreeMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(ru.spbu.astro.Schema.msg.RTreeMessage other) {
          if (other == ru.spbu.astro.Schema.msg.RTreeMessage.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
            }
          }
        }
        
        
        // @@protoc_insertion_point(builder_scope:ru.spbu.astro.msg.RTreeMessage)
      }
      
      static {
        defaultInstance = new RTreeMessage(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:ru.spbu.astro.msg.RTreeMessage)
    }
    
    private int bitField0_;
    // repeated .ru.spbu.astro.msg sons = 1;
    public static final int SONS_FIELD_NUMBER = 1;
    private java.util.List<ru.spbu.astro.Schema.msg> sons_;
    public java.util.List<ru.spbu.astro.Schema.msg> getSonsList() {
      return sons_;
    }
    public java.util.List<? extends ru.spbu.astro.Schema.msgOrBuilder> 
        getSonsOrBuilderList() {
      return sons_;
    }
    public int getSonsCount() {
      return sons_.size();
    }
    public ru.spbu.astro.Schema.msg getSons(int index) {
      return sons_.get(index);
    }
    public ru.spbu.astro.Schema.msgOrBuilder getSonsOrBuilder(
        int index) {
      return sons_.get(index);
    }
    
    // optional .ru.spbu.astro.msg.RTreeMessage rTree = 2;
    public static final int RTREE_FIELD_NUMBER = 2;
    private ru.spbu.astro.Schema.msg.RTreeMessage rTree_;
    public boolean hasRTree() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ru.spbu.astro.Schema.msg.RTreeMessage getRTree() {
      return rTree_;
    }
    public ru.spbu.astro.Schema.msg.RTreeMessageOrBuilder getRTreeOrBuilder() {
      return rTree_;
    }
    
    private void initFields() {
      sons_ = java.util.Collections.emptyList();
      rTree_ = ru.spbu.astro.Schema.msg.RTreeMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sons_.size(); i++) {
        output.writeMessage(1, sons_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, rTree_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < sons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sons_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rTree_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ru.spbu.astro.Schema.msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.spbu.astro.Schema.msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.spbu.astro.Schema.msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.spbu.astro.Schema.msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.spbu.astro.Schema.msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.spbu.astro.Schema.msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ru.spbu.astro.Schema.msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.spbu.astro.Schema.msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.spbu.astro.Schema.msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.spbu.astro.Schema.msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.spbu.astro.Schema.msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.spbu.astro.Schema.msgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbu.astro.Schema.internal_static_ru_spbu_astro_msg_fieldAccessorTable;
      }
      
      // Construct using ru.spbu.astro.Schema.msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSonsFieldBuilder();
          getRTreeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (sonsBuilder_ == null) {
          sons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sonsBuilder_.clear();
        }
        if (rTreeBuilder_ == null) {
          rTree_ = ru.spbu.astro.Schema.msg.RTreeMessage.getDefaultInstance();
        } else {
          rTreeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbu.astro.Schema.msg.getDescriptor();
      }
      
      public ru.spbu.astro.Schema.msg getDefaultInstanceForType() {
        return ru.spbu.astro.Schema.msg.getDefaultInstance();
      }
      
      public ru.spbu.astro.Schema.msg build() {
        ru.spbu.astro.Schema.msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ru.spbu.astro.Schema.msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ru.spbu.astro.Schema.msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ru.spbu.astro.Schema.msg buildPartial() {
        ru.spbu.astro.Schema.msg result = new ru.spbu.astro.Schema.msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (sonsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sons_ = java.util.Collections.unmodifiableList(sons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sons_ = sons_;
        } else {
          result.sons_ = sonsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (rTreeBuilder_ == null) {
          result.rTree_ = rTree_;
        } else {
          result.rTree_ = rTreeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbu.astro.Schema.msg) {
          return mergeFrom((ru.spbu.astro.Schema.msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ru.spbu.astro.Schema.msg other) {
        if (other == ru.spbu.astro.Schema.msg.getDefaultInstance()) return this;
        if (sonsBuilder_ == null) {
          if (!other.sons_.isEmpty()) {
            if (sons_.isEmpty()) {
              sons_ = other.sons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSonsIsMutable();
              sons_.addAll(other.sons_);
            }
            onChanged();
          }
        } else {
          if (!other.sons_.isEmpty()) {
            if (sonsBuilder_.isEmpty()) {
              sonsBuilder_.dispose();
              sonsBuilder_ = null;
              sons_ = other.sons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sonsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSonsFieldBuilder() : null;
            } else {
              sonsBuilder_.addAllMessages(other.sons_);
            }
          }
        }
        if (other.hasRTree()) {
          mergeRTree(other.getRTree());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ru.spbu.astro.Schema.msg.Builder subBuilder = ru.spbu.astro.Schema.msg.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSons(subBuilder.buildPartial());
              break;
            }
            case 18: {
              ru.spbu.astro.Schema.msg.RTreeMessage.Builder subBuilder = ru.spbu.astro.Schema.msg.RTreeMessage.newBuilder();
              if (hasRTree()) {
                subBuilder.mergeFrom(getRTree());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRTree(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .ru.spbu.astro.msg sons = 1;
      private java.util.List<ru.spbu.astro.Schema.msg> sons_ =
        java.util.Collections.emptyList();
      private void ensureSonsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sons_ = new java.util.ArrayList<ru.spbu.astro.Schema.msg>(sons_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          ru.spbu.astro.Schema.msg, ru.spbu.astro.Schema.msg.Builder, ru.spbu.astro.Schema.msgOrBuilder> sonsBuilder_;
      
      public java.util.List<ru.spbu.astro.Schema.msg> getSonsList() {
        if (sonsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sons_);
        } else {
          return sonsBuilder_.getMessageList();
        }
      }
      public int getSonsCount() {
        if (sonsBuilder_ == null) {
          return sons_.size();
        } else {
          return sonsBuilder_.getCount();
        }
      }
      public ru.spbu.astro.Schema.msg getSons(int index) {
        if (sonsBuilder_ == null) {
          return sons_.get(index);
        } else {
          return sonsBuilder_.getMessage(index);
        }
      }
      public Builder setSons(
          int index, ru.spbu.astro.Schema.msg value) {
        if (sonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSonsIsMutable();
          sons_.set(index, value);
          onChanged();
        } else {
          sonsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSons(
          int index, ru.spbu.astro.Schema.msg.Builder builderForValue) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.set(index, builderForValue.build());
          onChanged();
        } else {
          sonsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSons(ru.spbu.astro.Schema.msg value) {
        if (sonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSonsIsMutable();
          sons_.add(value);
          onChanged();
        } else {
          sonsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSons(
          int index, ru.spbu.astro.Schema.msg value) {
        if (sonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSonsIsMutable();
          sons_.add(index, value);
          onChanged();
        } else {
          sonsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSons(
          ru.spbu.astro.Schema.msg.Builder builderForValue) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.add(builderForValue.build());
          onChanged();
        } else {
          sonsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSons(
          int index, ru.spbu.astro.Schema.msg.Builder builderForValue) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.add(index, builderForValue.build());
          onChanged();
        } else {
          sonsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSons(
          java.lang.Iterable<? extends ru.spbu.astro.Schema.msg> values) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          super.addAll(values, sons_);
          onChanged();
        } else {
          sonsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSons() {
        if (sonsBuilder_ == null) {
          sons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sonsBuilder_.clear();
        }
        return this;
      }
      public Builder removeSons(int index) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.remove(index);
          onChanged();
        } else {
          sonsBuilder_.remove(index);
        }
        return this;
      }
      public ru.spbu.astro.Schema.msg.Builder getSonsBuilder(
          int index) {
        return getSonsFieldBuilder().getBuilder(index);
      }
      public ru.spbu.astro.Schema.msgOrBuilder getSonsOrBuilder(
          int index) {
        if (sonsBuilder_ == null) {
          return sons_.get(index);  } else {
          return sonsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends ru.spbu.astro.Schema.msgOrBuilder> 
           getSonsOrBuilderList() {
        if (sonsBuilder_ != null) {
          return sonsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sons_);
        }
      }
      public ru.spbu.astro.Schema.msg.Builder addSonsBuilder() {
        return getSonsFieldBuilder().addBuilder(
            ru.spbu.astro.Schema.msg.getDefaultInstance());
      }
      public ru.spbu.astro.Schema.msg.Builder addSonsBuilder(
          int index) {
        return getSonsFieldBuilder().addBuilder(
            index, ru.spbu.astro.Schema.msg.getDefaultInstance());
      }
      public java.util.List<ru.spbu.astro.Schema.msg.Builder> 
           getSonsBuilderList() {
        return getSonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ru.spbu.astro.Schema.msg, ru.spbu.astro.Schema.msg.Builder, ru.spbu.astro.Schema.msgOrBuilder> 
          getSonsFieldBuilder() {
        if (sonsBuilder_ == null) {
          sonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ru.spbu.astro.Schema.msg, ru.spbu.astro.Schema.msg.Builder, ru.spbu.astro.Schema.msgOrBuilder>(
                  sons_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sons_ = null;
        }
        return sonsBuilder_;
      }
      
      // optional .ru.spbu.astro.msg.RTreeMessage rTree = 2;
      private ru.spbu.astro.Schema.msg.RTreeMessage rTree_ = ru.spbu.astro.Schema.msg.RTreeMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ru.spbu.astro.Schema.msg.RTreeMessage, ru.spbu.astro.Schema.msg.RTreeMessage.Builder, ru.spbu.astro.Schema.msg.RTreeMessageOrBuilder> rTreeBuilder_;
      public boolean hasRTree() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public ru.spbu.astro.Schema.msg.RTreeMessage getRTree() {
        if (rTreeBuilder_ == null) {
          return rTree_;
        } else {
          return rTreeBuilder_.getMessage();
        }
      }
      public Builder setRTree(ru.spbu.astro.Schema.msg.RTreeMessage value) {
        if (rTreeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rTree_ = value;
          onChanged();
        } else {
          rTreeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setRTree(
          ru.spbu.astro.Schema.msg.RTreeMessage.Builder builderForValue) {
        if (rTreeBuilder_ == null) {
          rTree_ = builderForValue.build();
          onChanged();
        } else {
          rTreeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeRTree(ru.spbu.astro.Schema.msg.RTreeMessage value) {
        if (rTreeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              rTree_ != ru.spbu.astro.Schema.msg.RTreeMessage.getDefaultInstance()) {
            rTree_ =
              ru.spbu.astro.Schema.msg.RTreeMessage.newBuilder(rTree_).mergeFrom(value).buildPartial();
          } else {
            rTree_ = value;
          }
          onChanged();
        } else {
          rTreeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearRTree() {
        if (rTreeBuilder_ == null) {
          rTree_ = ru.spbu.astro.Schema.msg.RTreeMessage.getDefaultInstance();
          onChanged();
        } else {
          rTreeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public ru.spbu.astro.Schema.msg.RTreeMessage.Builder getRTreeBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRTreeFieldBuilder().getBuilder();
      }
      public ru.spbu.astro.Schema.msg.RTreeMessageOrBuilder getRTreeOrBuilder() {
        if (rTreeBuilder_ != null) {
          return rTreeBuilder_.getMessageOrBuilder();
        } else {
          return rTree_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ru.spbu.astro.Schema.msg.RTreeMessage, ru.spbu.astro.Schema.msg.RTreeMessage.Builder, ru.spbu.astro.Schema.msg.RTreeMessageOrBuilder> 
          getRTreeFieldBuilder() {
        if (rTreeBuilder_ == null) {
          rTreeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ru.spbu.astro.Schema.msg.RTreeMessage, ru.spbu.astro.Schema.msg.RTreeMessage.Builder, ru.spbu.astro.Schema.msg.RTreeMessageOrBuilder>(
                  rTree_,
                  getParentForChildren(),
                  isClean());
          rTree_ = null;
        }
        return rTreeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:ru.spbu.astro.msg)
    }
    
    static {
      defaultInstance = new msg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ru.spbu.astro.msg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spbu_astro_msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_spbu_astro_msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spbu_astro_msg_RTreeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_spbu_astro_msg_RTreeMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Schema.proto\022\rru.spbu.astro\"g\n\003msg\022 \n\004" +
      "sons\030\001 \003(\0132\022.ru.spbu.astro.msg\022.\n\005rTree\030" +
      "\002 \001(\0132\037.ru.spbu.astro.msg.RTreeMessage\032\016" +
      "\n\014RTreeMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ru_spbu_astro_msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ru_spbu_astro_msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_spbu_astro_msg_descriptor,
              new java.lang.String[] { "Sons", "RTree", },
              ru.spbu.astro.Schema.msg.class,
              ru.spbu.astro.Schema.msg.Builder.class);
          internal_static_ru_spbu_astro_msg_RTreeMessage_descriptor =
            internal_static_ru_spbu_astro_msg_descriptor.getNestedTypes().get(0);
          internal_static_ru_spbu_astro_msg_RTreeMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ru_spbu_astro_msg_RTreeMessage_descriptor,
              new java.lang.String[] { },
              ru.spbu.astro.Schema.msg.RTreeMessage.class,
              ru.spbu.astro.Schema.msg.RTreeMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
